export interface StyleGroup {
  label: string;
  styles: { id: string; label: string }[];
}

function slug(label: string): string {
  return label
    .toLowerCase()
    .replace(/['']/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function group(label: string, items: string[]): StyleGroup {
  return { label, styles: items.map(l => ({ id: slug(l), label: l })) };
}

export const TRAVEL_STYLE_GROUPS: StyleGroup[] = [
  group("LUXURY", [
    "Boutique Luxury",
    "Ultra Luxury",
    "Luxury Family",
    "Luxury Wellness",
    "Luxury Adventure",
    "Luxury Chill",
    "Design Hotels",
    "Private Villa",
    "Castle & Estate",
    "Treehouse & Overwater",
    "Safari & Expedition",
    "Superyacht & Charter",
    "Private Aviation",
    "Members Club",
  ]),
  group("FOOD & DRINK", [
    "Foodie",
    "Michelin Star Dining",
    "Chef's Table & Omakase",
    "Fine Dining",
    "Local & Authentic",
    "Street Food Explorer",
    "Farm to Table",
    "Wine Country",
    "Champagne & Cellar Tours",
    "Whisky & Distillery",
    "Craft Beer & Breweries",
    "Culinary Classes",
    "Food Market Explorer",
    "Zero Waste Dining",
    "Vegetarian & Vegan",
    "Plant-Based Only",
    "Halal-Friendly",
    "Kosher-Friendly",
    "Gluten-Free Travel",
    "Allergy-Aware",
  ]),
  group("FAMILY", [
    "Luxury Family",
    "Active Family",
    "Beach Family",
    "Disney & Theme Parks",
    "Multi-Generational",
    "Baby & Toddler",
    "Kids Club & Resort",
    "Teen Travel",
    "Educational Travel",
    "Summer Camp Style",
    "Ski Family",
    "Sports Family",
    "Homeschool Travel",
  ]),
  group("PETS", [
    "Pet Friendly",
    "Dog Friendly Hotels",
    "Dog Friendly Beaches",
    "Pet Spa & Grooming",
    "Hiking with Dogs",
    "Pet-Friendly Airlines",
    "Ranch & Farm Stays",
    "Horse Riding Travel",
  ]),
  group("WELLNESS", [
    "Spa & Wellness",
    "Medical Wellness",
    "Yoga Retreat",
    "Meditation & Mindfulness",
    "Fitness & Bootcamp",
    "Thermal & Hot Springs",
    "Ayurveda",
    "Digital Detox",
    "Sleep Tourism",
    "Mental Health Travel",
    "Longevity & Biohacking",
    "Sober Travel",
    "Grief & Healing Retreats",
  ]),
  group("ADVENTURE & OUTDOORS", [
    "Hiking & Trekking",
    "Water Sports",
    "Skiing & Snow",
    "Heli-Skiing",
    "Surf Travel",
    "Diving & Snorkeling",
    "Freediving",
    "Cycling Tours",
    "Safari & Wildlife",
    "Climbing & Via Ferrata",
    "River & Sea Kayaking",
    "White Water Rafting",
    "Fly Fishing",
    "Hunting Travel",
    "Stargazing & Dark Sky",
    "Volcano & Geology",
    "Polar & Arctic",
    "Desert Expeditions",
  ]),
  group("WATER & SAILING", [
    "Cruise",
    "Luxury Cruise",
    "Expedition Cruise",
    "River Cruise",
    "Sailing",
    "Superyacht Charter",
    "Catamaran",
    "Bareboat Charter",
    "Overwater Bungalow",
    "Island Hopping",
    "Beach Club",
    "All Inclusive Resort",
    "Swim-Up Bar Life",
  ]),
  group("CULTURE & SLOW TRAVEL", [
    "Art & Museum",
    "Architecture",
    "History & Heritage",
    "UNESCO Sites",
    "Local Immersion",
    "Slow Travel",
    "Voluntourism",
    "Spiritual & Pilgrimage",
    "Language Immersion",
    "Rural & Agriturismo",
    "Residency & Long Stay",
    "Workation",
    "Digital Nomad",
    "Literary Travel",
    "Film & TV Locations",
    "Music & Jazz",
    "Festival & Events",
    "Fashion & Shopping",
  ]),
  group("SOCIAL & IDENTITY", [
    "LGBTQ+ Travel",
    "LGBTQ+ Family",
    "Gay-Friendly Resorts",
    "Girls Trip",
    "Bachelorette & Hen",
    "Couples Getaway",
    "Honeymoon",
    "Anniversary Travel",
    "Solo Female Travel",
    "Solo Travel",
    "Group Travel",
    "Friends Reunion",
    "Sports Travel",
    "Fan & Concert Travel",
    "Influencer & Content",
  ]),
  group("ECO & CONSCIOUS", [
    "Eco Travel",
    "Carbon Conscious",
    "Wildlife Conservation",
    "Regenerative Travel",
    "Off-Grid",
    "National Parks",
    "Plastic-Free Travel",
    "Community Tourism",
    "B Corp Hotels",
    "1% for the Planet",
    "Zero Footprint",
  ]),
  group("ACCESSIBILITY", [
    "Wheelchair Accessible",
    "Mobility Aid Friendly",
    "Sensory-Friendly",
    "Deaf-Friendly",
    "Blind & Low Vision",
    "Chronic Illness Travel",
    "Autism-Friendly",
    "Carer & Companion Travel",
  ]),
  group("TRANSPORT & STYLE", [
    "Business Class",
    "First Class",
    "Private Aviation",
    "Train Travel",
    "Orient Express Style",
    "Road Trip",
    "Campervan & RV",
    "Motorcycle Tour",
    "Cycling Country to Country",
    "Rickshaw & Tuk-Tuk",
    "Helicopter Transfers",
  ]),
  group("POOL & BEACH", [
    "Infinity Pool",
    "Adults Only Pool",
    "Pool Bar & Cabanas",
    "Family Pool",
    "Rooftop Pool",
    "Sandy Beach Access",
    "Private Beach",
    "Beach Club",
    "Crystal Clear Water",
    "Overwater Bungalow",
    "Rocky & Scenic Coast",
    "Snorkel & Reef Access",
    "Watersports Beach",
    "Nude Beach",
    "Secluded Cove",
  ]),
  group("AMENITIES I LOVE", [
    "Stunning Pool",
    "Ocean View Room",
    "Mountain View",
    "Garden & Grounds",
    "Historic Building",
    "Modern & Design-Led",
    "Outdoor Shower",
    "Private Plunge Pool",
    "Butler Service",
    "In-Room Dining",
    "Fireplace",
    "Bathtub with a View",
    "Outdoor Dining",
    "Farm & Kitchen Garden",
    "Helipad Access",
    "Private Villa Option",
    "Tennis Courts",
    "Golf Course",
    "Horseback Riding",
    "Kids Club",
  ]),
  group("STAY TYPE", [
    "Boutique Hotel",
    "All Inclusive",
    "Adult Only Resort",
    "Ryokan & Traditional Inn",
    "Riad & Medina",
    "Trulli & Cave Hotel",
    "Treehouse",
    "Overwater Bungalow",
    "Glamping",
    "Houseboat",
    "Castle & Chateau",
    "Monastery Stay",
    "Ranch & Dude Ranch",
    "Lighthouse",
    "Container & Tiny House",
    "Ice Hotel",
    "Capsule Hotel",
  ]),
];
